<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>SilkySouls</RootNamespace>
    <AssemblyName>SilkySouls</AssemblyName>
    <ApplicationIcon>Assets\Silky.ico</ApplicationIcon>
    <LangVersion>12</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.0.0" PrivateAssets="all" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25103.5738" />
    <PackageReference Include="Fody" Version="6.8.2" PrivateAssets="all" />
    <PackageReference Include="H.Hooks" Version="1.7.0" />
    <PackageReference Include="WPF-UI" Version="4.0.2" />
    <PackageReference Include="WPF-UI.Abstractions" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LICENSE.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Include="FodyWeavers.xml" />
  </ItemGroup>
</Project>
